### ISSUE TITLE
完全没法用

### ISSUE THREAD

**Issue by fangkyi03** [ZhangPingFan/flutter_quickjs#1]
../../.pub-cache/hosted/pub.flutter-io.cn/ffi-0.1.3/lib/src/utf8.dart:23:7: Error: Struct 'Utf8' is empty. Empty structs are undefined behavior.
class Utf8 extends Struct {
      ^
../../.pub-cache/hosted/pub.flutter-io.cn/ffi-0.1.3/lib/src/utf16.dart:16:7: Error: Struct 'Utf16' is empty. Empty structs are undefined behavior.
class Utf16 extends Struct {
      ^
../../.pub-cache/hosted/pub.flutter-io.cn/ffi-0.1.3/lib/src/allocation.dart:47:33: Error: Expected type 'T' to be a valid and instantiated subtype of 'NativeType'.
  final int totalSize = count * sizeOf<T>();
                                ^

**Comment by ZhangPingFan** [comment]
您好，能否提供下你使用的flutter版本？flutter doctor看下。 @fangkyi03

**Comment by fangkyi03** [comment]
我把你的那个代码也clone了 一直报那个quickjs.h文件找不到 我感觉应该是你自己本地有配置 但是别人电脑没法用的
[✓] Flutter (Channel master, 1.27.0-9.0.pre.149, on macOS 11.3 20E5196f
    darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

**Comment by fangkyi03** [comment]
我这边另一个flutter-qjs那个package是可以跑的 虽然我是mac m1 但是我觉得应该不至于是m1的关系导致的无法使用

**Comment by ZhangPingFan** [comment]
@fangkyi03  
这里可能涉及两方面问题：
1. 如果是报quickjs.h文件找不到，请确认你电脑上的cocoapods版本是多少（pod --version），如较低请升级至1.10.0以上（sudo gem install cocoapods），然后重新开项目引用插件，或者把ios项目中的Runner.xcodeproj/project.pbxproj 和 Podfile.lock 两个文件还原到没使用pod安装之前
2. 如果是你一开始贴的报错，估计是flutter版本过新，插件依赖的ffi也要相应做更新才行，这个后续版本相对稳定之后我再更新一下

**Comment by fangkyi03** [comment]
希望能内部集成一些常用的库 如promise 这个我在qjs那边得不到反馈 其他都挺好实现的再去实现一个promise 的确有点本末倒置 其次想一些补丁文件之类的 我也很难直接把js执行以后就可以使用 这也会导致在复杂场景下很难有一个好的体验

**Comment by fangkyi03** [comment]
pod 我是 1.10.1

**Comment by ZhangPingFan** [comment]
> pod 我是 1.10.1

新开项目引入还是不行吗？还是报.h文件找不到？

**Comment by fangkyi03** [comment]
新开项目引入 就是报我最早发的 把你这个项目clone下来就报头文件不存在

**Comment by ZhangPingFan** [comment]
那可能是第2个原因，可以把flutter切回stable channel看看还有没有错？

> 新开项目引入 就是报我最早发的 把你这个项目clone下来就报头文件不存在

**Comment by fangkyi03** [comment]
我一直不用stable 因为这个我这边使用一直会报一些文件无法下载安装 只有master分支是最稳定的 我也不确定是否跟m1有关系
